### PR TITLE
feat: add rotation to label

### PR DESCRIPTION
**Pull request by gca-axelor**
RM#72834

### CODE REVIEW

**Comment by gca-axelor** [comment]
test SettingsScreen :

```
/*
 * Axelor Business Solutions
 *
 * Copyright (C) 2023 Axelor (<http://axelor.com>).
 *
 * This program is free software: you can redistribute it and/or  modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React, {useMemo} from 'react';
import {Dashboard} from '@axelor/aos-mobile-ui';

const DemoResponse = {
  version: 2,
  name: 'Partner',
  dashboardLineList: [
    {
      name: 'Line 0',
      chartList: [
        {
          chartType: 'line',
          chartName: 'Number of SO by status',
          mobileChartValueResponseList: [
            {
              label: 'Canceled',
              value: 0,
            },
            {
              label: 'Draft quotation',
              value: 1,
            },
            {
              label: 'Finalized quotation',
              value: 3,
            },
            {
              label: 'Order completed',
              value: 0,
            },
            {
              label: 'Order confirmed',
              value: 9,
            },
          ],
        },
        {
          chartType: 'bar',
          chartName: 'Sale order count by partner',
          mobileChartValueResponseList: [
            {
              label: 'T0001 - APOLLO',
              value: 1,
            },
            {
              label: 'T0002 - MICHEL Loic',
              value: 2,
            },
            {
              label: 'T0003 - GARCIA Daniel',
              value: 3,
            },
            {
              label: 'T0004 - DAVID Laurent',
              value: 4,
            },
            {
              label: 'T0005 - BLUEBERRY TELECOM',
              value: 5,
            },
            {
              label: 'T0006 - ROUSSEAU Élisabeth',
              value: 6,
            },
          ],
        },
      ],
    },
    {
      name: 'Line 1',
      chartList: [
        {
          chartType: 'pie',
          chartName: 'Number of SO by status',
          mobileChartValueResponseList: [
            {
              label: 'Canceled',
              value: 0,
            },
            {
              label: 'Draft quotation',
              value: 1,
            },
            {
              label: 'Finalized quotation',
              value: 3,
            },
            {
              label: 'Order completed',
              value: 0,
            },
            {
              label: 'Order confirmed',
              value: 9,
            },
          ],
        },
        {
          chartType: 'donut',
          chartName: 'Sale order count by partner',
          mobileChartValueResponseList: [
            {
              label: 'T0001 - APOLLO',
              value: 1,
            },
            {
              label: 'T0002 - MICHEL Loic',
              value: 0,
            },
            {
              label: 'T0003 - GARCIA Daniel',
              value: 0,
            },
            {
              label: 'T0004 - DAVID Laurent',
              value: 0,
            },
            {
              label: 'T0005 - BLUEBERRY TELECOM',
              value: 1,
            },
            {
              label: 'T0006 - ROUSSEAU Élisabeth',
              value: 0,
            },
          ],
        },
      ],
    },
    {
      name: 'Line 2',
      chartList: [
        {
          chartType: 'donut',
          chartName: 'Number of SO by status',
          mobileChartValueResponseList: [
            {
              label: 'Canceled',
              value: 0,
            },
            {
              label: 'Draft quotation',
              value: 1,
            },
            {
              label: 'Finalized quotation',
              value: 3,
            },
            {
              label: 'Order completed',
              value: 0,
            },
            {
              label: 'Order confirmed',
              value: 9,
            },
          ],
        },
        {
          chartType: 'bar',
          chartName: 'Sale order count by partner',
          mobileChartValueResponseList: [
            {
              label: 'T0001 - APOLLO',
              value: 1,
            },
            {
              label: 'T0002 - MICHEL Loic',
              value: 0,
            },
            {
              label: 'T0003 - GARCIA Daniel',
              value: 0,
            },
            {
              label: 'T0004 - DAVID Laurent',
              value: 0,
            },
            {
              label: 'T0005 - BLUEBERRY TELECOM',
              value: 1,
            },
            {
              label: 'T0006 - ROUSSEAU Élisabeth',
              value: 0,
            },
          ],
        },
        {
          chartType: 'pie',
          chartName: 'Sale order count by partner',
          mobileChartValueResponseList: [
            {
              label: 'T0001 - APOLLO',
              value: 1,
            },
            {
              label: 'T0002 - MICHEL Loic',
              value: 0,
            },
            {
              label: 'T0003 - GARCIA Daniel',
              value: 0,
            },
            {
              label: 'T0004 - DAVID Laurent',
              value: 0,
            },
            {
              label: 'T0005 - BLUEBERRY TELECOM',
              value: 1,
            },
            {
              label: 'T0006 - ROUSSEAU Élisabeth',
              value: 0,
            },
          ],
        },
      ],
    },
    {
      name: 'Line 2',
      chartList: [
        {
          chartType: 'line',
          chartName: 'Sale order count by partner',
          mobileChartValueResponseList: [
            {
              label: 'T0001 - APOLLO',
              value: 1,
            },
            {
              label: 'T0002 - MICHEL Loic',
              value: 0,
            },
            {
              label: 'T0003 - GARCIA Daniel',
              value: 0,
            },
            {
              label: 'T0004 - DAVID Laurent',
              value: 0,
            },
            {
              label: 'T0005 - BLUEBERRY TELECOM',
              value: 1,
            },
            {
              label: 'T0006 - ROUSSEAU Élisabeth',
              value: 0,
            },
          ],
        },
      ],
    },
  ],
};

const SettingsScreen = ({}) => {
  const demoRefactor = useMemo(() => {
    const lineList = DemoResponse.dashboardLineList.map(elt => {
      const dataList = elt.chartList.map(ch => {
        return {
          type: ch.chartType,
          dataList: [ch.mobileChartValueResponseList],
          title: ch?.chartName,
        };
      });
      return {graphList: dataList};
    });

    return lineList;
  }, []);

  return <Dashboard lineList={demoRefactor} />;
};

export default SettingsScreen;

```

**Review by vhu-axelor — APPROVED** [review]
Nice work! 🔥

**Comment by lme-axelor** [comment]
Margin above title is not good when props is desactivated
Try to generalize the code, both chart need the same informations. 
When prop is desactivated, labels are stuck together
Label is not centered when rotated in BarChart

**Review by vhu-axelor — CHANGES_REQUESTED** [review]
Nice work! Just few things about LineChart component:
- margin above title is not good when rotateLabel props is false
- to harmonized the code try to put labelTextstyle in the helper

**Review by vhu-axelor — APPROVED** [review]
Very good job!

**Pull request merged**
